heat_template_version: 2013-05-23

description: >
  HOT template to create a new neutron network plus a router to the public
  network, and for deploying two Windows 11 (hostname cl1 and mgr) and two Windows
  Servers (hostnames dc1 and srv1) without any configuration (only cl1 has
  a boot script to set correct hostname).

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers

resources:
  private_net:
    type: OS::Neutron::Net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 192.168.111.0/24
      gateway_ip: 192.168.111.1
      allocation_pools:
        - start: 192.168.111.101
          end: 192.168.111.200

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: ntnu-internal

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  sec_core:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security group rules for all
      name: sec_core
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 3389
          port_range_max: 3389
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 5985
          port_range_max: 5985
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 5986
          port_range_max: 5986

  mgr:
    type: OS::Nova::Server
    properties:
      name: mgr
      image: 'Windows 11 24H2 Enterprise [Evaluation]'
      flavor: gx3.4c16r
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: mgr_port }
      user_data_format: RAW
  mgr_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      security_groups:
        - default
        - { get_resource: sec_core }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }
  mgr_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ntnu-internal
      port_id: { get_resource: mgr_port }

outputs:
  mgr_private_ip:
    description: IP address of mgr in private network
    value: { get_attr: [ mgr, first_address ] }
  mgr_public_ip:
    description: Floating IP address of mgr in public network
    value: { get_attr: [ mgr_floating_ip, floating_ip_address ] }
